#--------------------------------------------------------------#
#                                                              #
#                       AntiPiglinTrade                        #
#            Made by: https://github.com/Steven-OS             #
#                                                              #
#--------------------------------------------------------------#

# Decide which world the plugin will stop piglin trading.
# If you want to allow piglin trade in a specific world,
# simply remove it from the list below.

world-list:
  - world
  - world_nether
  - world_the_end

error-message: "&cPiglin bartering is disabled."

#--------------------------------------------------------------#
#                                                              #
#                      Auto Update Config                      #
#                                                              #
#--------------------------------------------------------------#
# Automatically update and override the config settings if
# there is a new update that contains a new setting.

# true: The plugin will reset this config.yml file to
# add new settings when they are released.

# false: The plugin will NOT reset this config.yml, but you will
# need to manually add the new options when they are released.

enable-update-config: false

#--------------------------------------------------------------#
#                                                              #
#                           bStats                             #
#                                                              #
#--------------------------------------------------------------#
# Collects statistics to improve the plugin.
# It does not impact performance; recommended to set to 'true'.

enable-bstats: true

#--------------------------------------------------------------#
#                                                              #
#                          Version                             #
#                                                              #
#--------------------------------------------------------------#
# Do not touch this option; the plugin will break.
version: 1.0